Alias: $loinc = http://loinc.org
Alias: $v3-NullFlavor = http://terminology.hl7.org/CodeSystem/v3-NullFlavor
Alias: $v3-RoleCode = http://terminology.hl7.org/CodeSystem/v3-RoleCode
Alias: $unitsofmeasure = http://unitsofmeasure.org
Alias: $v2-0136 = http://terminology.hl7.org/CodeSystem/v2-0136
Alias: $sct = http://snomed.info/sct
Alias: $observation-category = http://terminology.hl7.org/CodeSystem/observation-category
// Alias: $v2-0005 = RaceAndEthnicityCDC // http://terminology.hl7.org/CodeSystem/v2-0005
Alias: $v3-Ethnicity = http://terminology.hl7.org/CodeSystem/v3-Ethnicity
Alias: $v2-0203 = http://terminology.hl7.org/CodeSystem/v2-0203
Alias: $v2-0532 = http://terminology.hl7.org/CodeSystem/v2-0532
Alias: $CodeSystem-local-component-codes = CodesystemLocalComponentCodes 
Alias: $CodeSystem-birth-and-fetal-death-financial-class = CodesystemLocalComponentCodes 
Alias: $CodeSystem-vr-fetal-death-cause-or-condition = CodesystemLocalComponentCodes 

Alias: $Extension-partial-date-time = ExtensionPartialDateTimeVitalRecords //// http://hl7.org/fhir/us/vr-common-library/StructureDefinition/Extension-partial-date-time
Alias: $Extension-date-year = ExtensionDateYearVitalRecords // http://hl7.org/fhir/us/vr-common-library/StructureDefinition/Extension-date-year
Alias: $Extension-date-month = ExtensionDateMonthVitalRecords // http://hl7.org/fhir/us/vr-common-library/StructureDefinition/Extension-date-month
Alias: $Extension-date-day = ExtensionDateDayVitalRecords //http://hl7.org/fhir/us/vr-common-library/StructureDefinition/Extension-date-day
Alias: $Extension-date-time = ExtensionDateTimeVitalRecords //  http://hl7.org/fhir/us/vr-common-library/StructureDefinition/Extension-date-time
Alias: $patient-birthPlace = http://hl7.org/fhir/StructureDefinition/patient-birthPlace
Alias: $data-absent-reason = http://hl7.org/fhir/StructureDefinition/data-absent-reason
Alias: $patient-birthTime = http://hl7.org/fhir/StructureDefinition/patient-birthTime

Alias: $ValueSet-yes-no-unknown = ValueSetYesNoUnknownVitalRecords
Alias: $ValueSet-yes-no-unknown-not-applicable = ValueSetYesNoUnknownNotApplicableVitalRecords
Alias: $ValueSet-date-establishment-approach = ValueSetDateEstablishmentApproachVitalRecords
Alias: $ValueSet-place-of-death = ValueSetPlaceOfDeathVitalRecords
Alias: $ValueSet-death-pregnancy-status = ValueSetPregnancyStatusVitalRecords
Alias: $ValueSet-transportation-incident-role = ValueSetTransportationIncidentRoleVitalRecords
Alias: $ValueSet-manner-of-death = ValueSetMannerOfDeathVitalRecords
Alias: $v3-Ethnicity_1 = http://terminology.hl7.org/ValueSet/v3-Ethnicity
Alias: $ValueSet-contributory-tobacco-use = ValueSetContributoryTobaccoUse //http://hl7.org/fhir/us/vr-common-library/ValueSet/ValueSet-contributory-tobacco-use
Alias: $ValueSet-certifier-types = ValueSetCertifierTypes // http://hl7.org/fhir/us/vr-common-library/ValueSet/ValueSet-certifier-types